# 1.4.4 Smoothing Images

## Kernel Convolution

In [2]:
import cv2
import numpy as np
from matplotlib import pyplot as plt

In [3]:
l=1
kernel = np.array([[0,-1,0],[-1,4,-1],[0,-1,0]],np.float32)

In [4]:
kernel

array([[ 0., -1.,  0.],
       [-1.,  4., -1.],
       [ 0., -1.,  0.]], dtype=float32)

In [5]:
img = np.random.randint(10, size=(12,12))
#img = np.ones((10,10),np.float32)

In [6]:
img

array([[0, 6, 4, 8, 0, 3, 1, 9, 6, 7, 4, 8],
       [9, 0, 8, 8, 6, 3, 3, 6, 8, 4, 2, 1],
       [9, 5, 5, 6, 1, 4, 7, 8, 8, 5, 7, 7],
       [8, 3, 3, 0, 7, 4, 3, 1, 0, 0, 0, 9],
       [8, 4, 0, 3, 7, 4, 4, 9, 4, 5, 3, 5],
       [8, 9, 9, 2, 1, 8, 5, 5, 2, 1, 1, 3],
       [2, 6, 6, 5, 1, 9, 1, 5, 9, 2, 3, 5],
       [1, 2, 3, 6, 2, 7, 1, 5, 5, 3, 0, 3],
       [3, 9, 4, 2, 6, 2, 6, 0, 4, 2, 6, 5],
       [0, 1, 4, 0, 6, 7, 7, 1, 4, 9, 9, 2],
       [7, 9, 4, 5, 0, 2, 2, 1, 7, 7, 3, 9],
       [7, 2, 0, 5, 3, 2, 2, 4, 5, 4, 5, 8]])

In [7]:
h,w=img.shape

In [8]:
l=1
kernel = np.array([[0,-1,0],[-1,5,-1],[0,-1,0]],np.float32)

In [9]:
print(h,w)

12 12


In [10]:
#[*range(-2,3)]

In [11]:
dst = np.zeros((h,w),np.int)

In [12]:
for i in range(l,h-l):
    for j in range(l,w-l):
        t=0
        for p in range(-l,l+1):
            for q in range(-l,l+1):
                t += kernel[p+l,q+l]*img[i+p,j+q]
        dst[i,j]=t        

In [13]:
img

array([[0, 6, 4, 8, 0, 3, 1, 9, 6, 7, 4, 8],
       [9, 0, 8, 8, 6, 3, 3, 6, 8, 4, 2, 1],
       [9, 5, 5, 6, 1, 4, 7, 8, 8, 5, 7, 7],
       [8, 3, 3, 0, 7, 4, 3, 1, 0, 0, 0, 9],
       [8, 4, 0, 3, 7, 4, 4, 9, 4, 5, 3, 5],
       [8, 9, 9, 2, 1, 8, 5, 5, 2, 1, 1, 3],
       [2, 6, 6, 5, 1, 9, 1, 5, 9, 2, 3, 5],
       [1, 2, 3, 6, 2, 7, 1, 5, 5, 3, 0, 3],
       [3, 9, 4, 2, 6, 2, 6, 0, 4, 2, 6, 5],
       [0, 1, 4, 0, 6, 7, 7, 1, 4, 9, 9, 2],
       [7, 9, 4, 5, 0, 2, 2, 1, 7, 7, 3, 9],
       [7, 2, 0, 5, 3, 2, 2, 4, 5, 4, 5, 8]])

In [14]:
dst

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0, -28,  23,  12,  18,  -1,  -2,   2,  16,  -2,  -6,   0],
       [  0,   8,   3,  16, -18,   5,  17,  18,  19,   6,  21,   0],
       [  0,  -5,   7, -19,  23,   2,  -1, -15, -13, -10, -19,   0],
       [  0,   0, -19,   6,  20,  -3,  -1,  31,   4,  17,   4,   0],
       [  0,  18,  28,  -8, -13,  21,   7,   4,  -9,  -5,  -5,   0],
       [  0,  11,   7,  10, -12,  28, -15,   5,  31,  -6,   7,   0],
       [  0,  -9,  -3,  18, -10,  21, -14,  14,   4,   6, -15,   0],
       [  0,  35,   2,  -6,  18, -16,  20, -16,   9, -12,  14,   0],
       [  0, -17,  11, -17,  17,  18,  19,  -7,  -1,  23,  25,   0],
       [  0,  31,   2,  16, -16,  -1,  -2,  -9,  18,  12, -15,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0]])

In [15]:
img = cv2.imread('lena.png', 0)

In [16]:
h,w=img.shape

In [17]:
dst = np.zeros((h-2*l,w-2*l),np.uint8)

In [18]:
for i in range(l,h-l):
    for j in range(l,w-l):
        t=0
        for p in range(-l,l+1):
            for q in range(-l,l+1):
                t += kernel[p+l,q+l]*img[i+p,j+q]
        dst[i-l,j-l]=t 

In [19]:
cv2.imshow('img',img)
cv2.imshow('dst',dst)
cv2.waitKey(0)
cv2.destroyAllWindows()